---
language: generic
sudo: required
services:
  - docker

env:
  global:
#    - DOCKER_HUB_LOGIN
#    - DOCKER_HUB_PASSWORD
#    - DOCKER_HUB_REPO
    - SHORT_COMMIT="${TRAVIS_COMMIT:0:7}"
  matrix:
    - VERSION=7.2

before_install:
  - docker pull ${DOCKER_HUB_REPO}/php:${VERSION}-onbuild || true
  - docker pull ${DOCKER_HUB_REPO}/php:${VERSION} || true

script:
  - |
      docker build -t ${DOCKER_HUB_REPO}/php:${VERSION}-onbuild \
                   -f $TRAVIS_BUILD_DIR/${VERSION}/Dockerfile-onbuild \
                   --cache-from ${DOCKER_HUB_REPO}/php:${VERSION}-onbuild \
                   $TRAVIS_BUILD_DIR
  -   docker tag ${DOCKER_HUB_REPO}/php:${VERSION}-onbuild ${DOCKER_HUB_REPO}/php:${VERSION}-onbuild-${SHORT_COMMIT}

  - |
      docker build -t ${DOCKER_HUB_REPO}/php:${VERSION} \
                   -f $TRAVIS_BUILD_DIR/${VERSION}/Dockerfile \
                   --build-arg XDEBUG_ENABLED=true \
                   --cache-from ${DOCKER_HUB_REPO}/php:${VERSION} \
                   $TRAVIS_BUILD_DIR
  -   docker tag ${DOCKER_HUB_REPO}/php:${VERSION} ${DOCKER_HUB_REPO}/php:${VERSION}-${SHORT_COMMIT}

deploy:
  provider: script
  script: bin/deploy.sh
  on:
    branch: master
