#!/usr/bin/dumb-init sh
set -e

# Initialize user if not root.
userdel -f app &> /dev/null || true
groupdel -f app &> /dev/null || true

groupadd -o -g ${GID} app
useradd -K MAIL_DIR=/dev/null -u ${UID} -G app -o -d /app -M -N -s /sbin/nologin app 2>/dev/null

chown -RL app:app /var/lib/nginx /var/log/newrelic

# Execute any initialization scripts.
echo "Executing container initialization scripts."
for script_path in /etc/cont-init.d/*; do
    echo "  - ${script_path}"
	sh ${script_path}
done

# If no arguments provided, then start up the web server.
if [ "$1" = "" ]; then
    php-fpm -t -y $PHPRC/php-fpm.conf || exit 1
    nginx -t 2> /dev/null || exit 2

    echo -n "Starting web server... "
    php-fpm -F -y $PHPRC/php-fpm.conf &
    nginx &
    echo "done"

    trap "kill 0" INT KILL STOP TERM CHLD

    wait
else
	exec su-exec app "$@"
fi
