FROM alpine:3.8

WORKDIR /app

ENV NEWRELIC_VERSION="8.1.0.209" \
	PHP_VERSION="7.2.9-r1" \
	PHP_INI_DIR="/etc/php" \
	PHPRC="${PHP_INI_DIR}"

# Provide build arguments for configuration.
ONBUILD ARG UID=65534
ONBUILD ARG GID=65534

# NGiNX configuration.
ONBUILD ARG WEBROOT=/app
ONBUILD ARG TIMEOUT=60
ONBUILD ARG HSTS_ENABLED=false
ONBUILD ARG SSL_ENABLED=false
ONBUILD ARG SSL_CERT_DOWNLOAD_URL=""
ONBUILD ARG SSL_KEY_DOWNLOAD_URL=""

# PHP-FPM configuration.
ONBUILD ARG FPM_MAX_CHILDREN=0
ONBUILD ARG FPM_MAX_REQUESTS=1
ONBUILD ARG FPM_PM=static
ONBUILD ARG FPM_MIN_SPARE_SERVERS=5
ONBUILD ARG FPM_MAX_SPARE_SERVERS=15
ONBUILD ARG FPM_TIMEOUT=60

# PHP configuration.
ONBUILD ARG TIMEZONE="Etc/UTC"
ONBUILD ARG DISPLAY_ERRORS=Off
ONBUILD ARG ERROR_REPORTING="E_ALL & ~E_DEPRECATED & ~E_STRICT"
ONBUILD ARG HTML_ERRORS=Off
ONBUILD ARG MAX_EXECUTION_TIME=30
ONBUILD ARG MEMORY_LIMIT=32M
ONBUILD ARG POST_MAX_SIZE=8M
ONBUILD ARG SESSION_SAVE_HANDLER="files"
ONBUILD ARG SESSION_SAVE_PATH="/tmp/sessions"
ONBUILD ARG UPLOAD_MAX_FILESIZE=2M

ONBUILD ARG XDEBUG_ENABLED=false
ONBUILD ARG XDEBUG_IDE_KEY=IDEKEY
ONBUILD ARG XDEBUG_REMOTE_AUTOSTART=0
ONBUILD ARG XDEBUG_REMOTE_HOST=192.168.99.1
ONBUILD ARG XDEBUG_REMOTE_PORT=9000
ONBUILD ARG XDEBUG_SERVER_NAME="\$server_name"

ONBUILD ARG NEWRELIC_APP_NAME=""
ONBUILD ARG NEWRELIC_AUTORUM_ENABLED=0
ONBUILD ARG NEWRELIC_ENABLED=false
ONBUILD ARG NEWRELIC_LABELS=""
ONBUILD ARG NEWRELIC_LICENCE=""

# Set environment variables based on build arg values.
ONBUILD ENV \
	UID=${UID} \
    GID=${GID} \
	\
    WEBROOT=${WEBROOT} \
    NGINX_TIMEOUT=${NGINX_TIMEOUT} \
    \
	FPM_MAX_CHILDREN=${FPM_MAX_CHILDREN} \
    FPM_MAX_REQUESTS=${FPM_MAX_REQUESTS} \
    FPM_MAX_SPARE_SERVERS=${FPM_MAX_SPARE_SERVERS} \
    FPM_MIN_SPARE_SERVERS=${FPM_MIN_SPARE_SERVERS} \
    FPM_PM=${FPM_PM} \
    FPM_REQUEST_TERMINATE_TIMEOUT=${FPM_REQUEST_TERMINATE_TIMEOUT} \
    \
    TIMEZONE=${TIMEZONE} \
    DISPLAY_ERRORS=${DISPLAY_ERRORS} \
    ERROR_REPORTING=${ERROR_REPORTING} \
    HTML_ERRORS=${HTML_ERRORS} \
    MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME} \
    MEMORY_LIMIT=${MEMORY_LIMIT} \
    POST_MAX_SIZE=${POST_MAX_SIZE} \
    SESSION_SAVE_HANDLER=${SESSION_SAVE_HANDLER} \
    SESSION_SAVE_PATH=${SESSION_SAVE_PATH} \
    UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE} \
    \
    XDEBUG_IDE_KEY=${XDEBUG_IDE_KEY} \
    XDEBUG_REMOTE_AUTOSTART=${XDEBUG_REMOTE_AUTOSTART} \
    XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST} \
    XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT} \
    XDEBUG_SERVER_NAME=${XDEBUG_SERVER_NAME} \
    \
    NEWRELIC_APP_NAME=${NEWRELIC_APP_NAME} \
    NEWRELIC_AUTORUM_ENABLED=${NEWRELIC_AUTORUM_ENABLED} \
    NEWRELIC_LABELS=${NEWRELIC_LABELS} \
    NEWRELIC_LICENCE=${NEWRELIC_LICENCE}

# Ensure required directories exist.
RUN set -e; \
	mkdir -p /opt /app; \
	apk add --no-cache ca-certificates dumb-init su-exec nginx gettext openssl shadow;

# Install the PHP extensions already available in Alpine.
RUN set -e; \
	apk add --no-cache \
		php7 php7-amqp php7-apcu php7-bcmath php7-bz2 php7-ctype php7-curl \
		php7-dom php7-exif php7-fpm php7-fileinfo php7-ftp php7-gd php7-gettext php7-gmp \
		php7-iconv php7-intl php7-json php7-mbstring php7-memcached php7-mysqlnd php7-opcache \
		php7-openssl php7-pdo_mysql php7-pdo_sqlite php7-phar php7-redis php7-session php7-simplexml \
        php7-soap php7-sodium php7-sqlite3 php7-tokenizer php7-xml php7-xmlwriter php7-zip \
        php7-zlib; \
	rm -rf /etc/nginx $PHP_INI_DIR; \
    ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm; \
    ln -s /etc/php $PHP_INI_DIR; \
	mkdir -p /run/nginx /var/log/newrelic

COPY /fs /
ENTRYPOINT ["/init"]

# Download, clean up and symlink New Relic extension. Only if it is enabled.
ONBUILD RUN set -e; \
	if [ "$NEWRELIC_ENABLED" != "true" ]; then \
        rm $PHP_INI_DIR/conf.d/30-newrelic.ini.tpl; \
        exit 0; \
    fi; \
	wget https://download.newrelic.com/php_agent/archive/${NEWRELIC_VERSION}/newrelic-php5-${NEWRELIC_VERSION}-linux-musl.tar.gz -O- | tar -xz -C /tmp; \
	mv /tmp/newrelic-php5-${NEWRELIC_VERSION}-linux-musl /opt/newrelic; \
	find /opt/newrelic/agent/x64 -type f ! -name "newrelic-$(php -i | grep -F 'PHP Extension =' | sed -e 's/PHP Extension => //').so" -delete; \
	ln -s "$(find /opt/newrelic/agent/x64 -iname '*.so' | head -n 1)" $(php -r 'echo ini_get("extension_dir");')/newrelic.so;

# Install XDebug if enabled.
ONBUILD run set -e; \
    if [ "$XDEBUG_ENABLED" != "true" ]; then \
        rm $PHP_INI_DIR/conf.d/30-xdebug.ini.tpl; \
        exit 0; \
    fi; \
    apk add --no-cache php7-xdebug
